"""Add stock_quantity to products

Revision ID: 50bb3e21db2b
Revises: 0d65f4d28455
Create Date: 2025-01-09 14:22:30.330640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bb3e21db2b'
down_revision = '0d65f4d28455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###
