swagger: '2.0'
info:
  version: '1.0.0'
  title: Factory Management API - Analytics
  description: API documentation for analytics-related operations in the Factory Management System.
paths:
  /analytics/employee-performance:
    get:
      summary: Analyze employee performance
      description: Analyze the total quantity of products each employee has produced.
      responses:
        200:
          description: Success
        500:
          description: Internal server error
  /analytics/top-products:
    get:
      summary: Get top-selling products
      description: Fetch top-selling products based on total quantity ordered.
      responses:
        200:
          description: Success
        500:
          description: Internal server error
  /analytics/customer-lifetime-value:
    get:
      summary: Calculate customer lifetime value
      description: Calculate the total value of orders placed by each customer.
      parameters:
        - name: threshold
          in: query
          type: number
          description: Minimum total order value to filter customers (default: 1000)
      responses:
        200:
          description: Success
        400:
          description: Invalid threshold value
        500:
          description: Internal server error
  /analytics/production-efficiency:
    get:
      summary: Evaluate production efficiency
      description: Evaluate production efficiency by calculating the total quantity produced for each product on a specific date.
      parameters:
        - name: date
          in: query
          type: string
          description: Date in YYYY-MM-DD format (required)
      responses:
        200:
          description: Success
        400:
          description: Date is required
        500:
          description: Internal server error
